const ACTION_TYPES = {
    FETCH_STARTED: 'FETCH_STARTED',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_FAIL: 'FETCH_FAIL',
  };
  export default ACTION_TYPES;
  /* API_STARTED: 'API_STARTED',
    API_SUCCESS: 'API_SUCCESS',
    API_ERROR: 'API_ERROR', */